import type { NextPage } from "next";
import Head from "next/head";
import Todos from "../components/Todos";
import { useSession } from "next-auth/react";

const Home: NextPage = ({}) => {
	const { data: session, status } = useSession();

	return (
		<>
			<Head>
				<title>T3 Todo</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				{status === "loading" ? (
					<div className="h-screen w-screen flex justify-center items-center">
						Loading...
					</div>
				) : (
					<div>
						{status === "unauthenticated" ? (
							<div className="h-screen w-screen flex justify-center items-center">
								Login in First
							</div>
						) : (
							<Todos />
						)}
					</div>
				)}
			</main>
		</>
	);
};

export default Home;
